"""add bopa analysis and match tables

Revision ID: ba7534c97335
Revises: f7a1c2d3e4b5
Create Date: 2026-07-17 09:46:02.241082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba7534c97335'
down_revision = 'f7a1c2d3e4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bopa_analysis_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('matches_found', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bopa_bulletins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bopa_analysis_logs_bulletin_id'), 'bopa_analysis_logs', ['bulletin_id'], unique=True)
    op.create_index(op.f('ix_bopa_analysis_logs_id'), 'bopa_analysis_logs', ['id'], unique=False)
    op.create_table('bopa_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('matched_term', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['bopa_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'document_id', name='uq_bopa_match_customer_doc')
    )
    op.create_index(op.f('ix_bopa_matches_customer_id'), 'bopa_matches', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bopa_matches_document_id'), 'bopa_matches', ['document_id'], unique=False)
    op.create_index(op.f('ix_bopa_matches_id'), 'bopa_matches', ['id'], unique=False)
    op.create_index(op.f('ix_bopa_matches_project_id'), 'bopa_matches', ['project_id'], unique=False)
    op.drop_index(op.f('ix_task_notes_id'), table_name='task_notes')
    op.drop_index(op.f('ix_task_notes_task_id'), table_name='task_notes')
    op.drop_table('task_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('task_notes_author_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_notes_pkey'))
    )
    op.create_index(op.f('ix_task_notes_task_id'), 'task_notes', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_notes_id'), 'task_notes', ['id'], unique=False)
    op.drop_index(op.f('ix_bopa_matches_project_id'), table_name='bopa_matches')
    op.drop_index(op.f('ix_bopa_matches_id'), table_name='bopa_matches')
    op.drop_index(op.f('ix_bopa_matches_document_id'), table_name='bopa_matches')
    op.drop_index(op.f('ix_bopa_matches_customer_id'), table_name='bopa_matches')
    op.drop_table('bopa_matches')
    op.drop_index(op.f('ix_bopa_analysis_logs_id'), table_name='bopa_analysis_logs')
    op.drop_index(op.f('ix_bopa_analysis_logs_bulletin_id'), table_name='bopa_analysis_logs')
    op.drop_table('bopa_analysis_logs')
    # ### end Alembic commands ###

